### ISSUE TITLE
Any plans to implement functionality on the Fragment level?

### ISSUE THREAD

**Issue by mattblang** [dkharrat/NexusDialog#1]
For example, if using a ViewPager to switch between sections of the form it would be necessary to be able to add form sections and elements in each Fragment, rather than the Activity.

**Comment by dkharrat** [comment]
Just pushed a change that decouples the form management from the Activity. This means, you should now be able to use an Activity or Fragment.

**Comment by vijayphale** [comment]
Thanks a lot **@dkharrat**. I will definitely take a look at your changes.

**Comment by w0wka91** [comment]
Did anyone implemented the FormFragment and can share the code??

**Comment by w0wka91** [comment]
Got it already...

import w0wka91.com.pyload_remote.helpers.FormFragment;

public class EditPackageDialog extends FormFragment {

    @Override protected void initForm() {
        FormSectionController section = new FormSectionController(getActivity(), "Personal Info");
        section.addElement(new EditTextController(getActivity(), "firstName", "First name"));
        section.addElement(new EditTextController(getActivity(), "lastName", "Last name"));
        section.addElement(new SelectionController(getActivity(), "gender", "Gender", true, "Select", Arrays.asList("Male", "Female"), true));

        getFormController().addSection(section);

    }
}

**Comment by powellbird** [comment]
Thank you very much for the answer, someone could put the code of how to implement fragment with NexusDialog, thank you very much
