### ISSUE TITLE
Last value entered in every fields on screen rotation.

### ISSUE THREAD

**Issue by aveuiller** [dkharrat/NexusDialog#12]
On a screen rotation, the redraw will set the value of last field to every other fields

![before_rotation](https://cloud.githubusercontent.com/assets/4600261/10691590/7fd8d578-798a-11e5-9e7b-ba8bbd5ee05b.png)

![after_rotation](https://cloud.githubusercontent.com/assets/4600261/10691589/7fd6661c-798a-11e5-871c-574f2a247045.png)

**Comment by dkharrat** [comment]
Is this a dup of #11? Does it still happen when using unique view IDs?

**Comment by aveuiller** [comment]
I tried with different IDs on the fields and values are not reported on this case, so as you thought, 
the problem is probably the same as on the issue #11.

**Comment by dkharrat** [comment]
Closing as a dup of #11
