### ISSUE TITLE
FormFragment not function in pageadapter and tablayout

### ISSUE THREAD

**Issue by powellbird** [dkharrat/NexusDialog#32]
I have problems in implementing the new feature formFragment because by putting them in a PageAdapter and tablayout only displays the first page but the other tabs are blank, they could help me make the right implementation, thanks

**Comment by dkharrat** [comment]
I'm not sure I understand your question. Fragment support was recently implemented by @aveuiller and there's an example of how to use it in the samples directory. I recommend looking at the example code for usage. More details on the issue you're having would be helpful.

**Comment by powellbird** [comment]
thanks for the reply, when analyzing the FragmenFormActivity example, if I add a fragment more to supportfragmentmanager, only the first fragment is displayed in the form and others are not displayed correctly. Could you tell me how to put a frag in the same activity. Thank you

**Comment by powellbird** [comment]
thanks for the reply, when analyzing the FragmenFormActivity example, if I add a fragment more to supportfragmentmanager, only the first fragment is displayed in the form and others are not displayed correctly. Could you tell me how to put a frag in the same activity. Thank you

**Comment by powellbird** [comment]
thanks for the reply, when analyzing the FragmenFormActivity example, if I add a fragment more to supportfragmentmanager, only the first fragment is displayed in the form and others are not displayed correctly. Could you tell me how to put a frag in the same activity. Thank you

**Comment by powellbird** [comment]
thanks for the reply, when analyzing the FragmenFormActivity example, if I add a fragment more to supportfragmentmanager, only the first fragment is displayed in the form and others are not displayed correctly. Could you tell me how to put a frag in the same activity. Thank you

**Comment by powellbird** [comment]
gracias por la respuesta, al analizar el ejemplo FragmenFormActivity, si agrego un fragment mas al supportfragmentmanager, solo el primer fragment es desplegado en la forma y los demas no se despliegan correctamente. Podrian decirme como poner dos o mas  fragment en la misma activity. Gracias

**Comment by powellbird** [comment]
thanks for the reply, when analyzing the FragmenFormActivity example, if I add a fragment more to supportfragmentmanager, only the first fragment is displayed in the form and others are not displayed correctly. Could you tell me how to put two or more fragment in the same activity. Thank you

**Comment by aveuiller** [comment]
As you can [see in the sample](https://github.com/dkharrat/NexusDialog/blob/master/sample/src/main/java/com/github/dkharrat/nexusdialog/sample/FragmentFormActivity.java#L39), the fragment is here put in the element _fragment_container_, which is [defined in the layout](https://github.com/dkharrat/NexusDialog/blob/master/sample/src/main/res/layout/fragment_activity.xml#L20).

Have you tried creating a new `ViewHolder` like a `LinearLayout` and putting your second fragment into it with another add in the transaction?

**Comment by powellbird** [comment]
I did already the same for another fragment and only see the first, so try a tablayout with pageradapter and three TABS and it happens that the first TAB displays correct, but others are always blank and does not display correctly form. Greetings.
