### ISSUE TITLE
CheckBox only 2 options displays even added 4 options

### ISSUE THREAD

**Issue by chiragsudani** [dkharrat/NexusDialog#33]
I i have added checkbox control with 4 values, but it always display 2 checkbox.

**Comment by flibbertigibbet** [comment]
I believe this may be fixed by changing `match_parent` to `wrap_content` on the `layout_height` for the `LinearLayout` in `form_checkbox_container.xml` and the inner `LinearLayout` in `form_labeled_element.xml`.

**Comment by chiragsudani** [comment]
I tried same but not fixed..

**Comment by chiragsudani** [comment]
@flibbertigibbet thanks for replay, i have solved issue as per you suggestion.
