### ISSUE TITLE
fragmentForm feature error 

### ISSUE THREAD

**Issue by powellbird** [dkharrat/NexusDialog#43]
Good Afternoon.

Could you help me with the following error please.

FragmentForm property causes an error when using it with a FragmentPagerAdapter and a TabLayou and change Tab.

The error is a null as I show in the following text.

Com.github.dkharrat.nexusdialog.sample E / AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.github.dkharrat.nexusdialog.sample, PID: 2385
                                                                                      **## Java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.dkharrat.nexusdialog.FormElementController.refresh ()' on a null object reference**
                                                                                          At com.github.dkharrat.nexusdialog.FormController $ 1.propertyChange (FormController.java:248)
                                                                                          At java.beans.PropertyChangeSupport.firePropertyChange (PropertyChangeSupport.java:396)
                                                                                          At java.beans.PropertyChangeSupport.firePropertyChange (PropertyChangeSupport.java:88)
                                                                                          At com.github.dkharrat.nexusdialog.FormModel.setValue (FormModel.java:62)
                                                                                          At com.github.dkharrat.nexusdialog.controllers.EditTextController $ 1.afterTextChanged (EditTextController.java:202)
                                                                                          At android.widget.TextView.sendAfterTextChanged (TextView.java:8017)
                                                                                          At android.widget.TextView $ ChangeWatcher.afterTextChanged (TextView.java:10178)
                                                                                          At android.text.SpannableStringBuilder.sendAfterTextChanged (SpannableStringBuilder.java:1043)
                                                                                          At android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:560)
                                                                                          At android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:492)
                                                                                          At android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:491)
                                                                                          At android.view.inputmethod.BaseInputConnection.replaceText (BaseInputConnection.java:685)
                                                                                          At android.view.inputmethod.BaseInputConnection.setComposingText (BaseInputConnection.java:445)
                                                                                          At com.android.internal.view.IInputConnectionWrapper.executeMessage (IInputConnectionWrapper.java:340)
                                                                                          at

**Comment by powellbird** [comment]
Please help

**Comment by dkharrat** [comment]
Are you still getting this error in the latest release. I believe it should be fixed now.
