### ISSUE TITLE
right to left 

### ISSUE THREAD

**Issue by ghazalarabi** [dkharrat/NexusDialog#46]
Hello,
could you please tell me how to change direction of controls?
For example i would like to set direction of EditTextController to right to left . is it possible?

**Comment by dkharrat** [comment]
Unfortunately, RTL support was not a consideration when I developed this library. To support it, I believe it would mostly require changing the layout XML files to use the proper tags that are RTL-aware.

A pull-request to fix this is most welcome :)

**Comment by flibbertigibbet** [comment]
For API levels 17+, Android will mostly do the right thing during layout based on the system locale, but for lower API levels it can be difficult to get working.

For an example of how this may be done, you might want to look over [here](https://github.com/WorldBank-Transport/DRIVER-Android/pull/42/files#diff-680a726738fa88442412feb04e8e205bR40). The project is using a modified version of this form-builder library, with RTL layout and a different calendar, based on locale.

**Comment by ghazalarabi** [comment]
thanks for replying but still have problem with RTL. how it is possible in FormElementControllers?

for example:i want to have "First name" in the right side.
 section.addElement(new EditTextController(this, FIRST_NAME, "First name", "Change me", true));

**Comment by dkharrat** [comment]
Did you add the `android:supportsRtl="true"` flag to your `AndroidManifest.xml`? That should work assuming your `targetSdkVersion` is 17 or higher.

**Comment by ghazalarabi** [comment]
yes i have done that and my targetSdkVersion is 19 .
i did send my sample code with it's run . in Persian language i need all the text to be the right side.
![11 copy](https://cloud.githubusercontent.com/assets/8850937/21073517/b73baac0-bef5-11e6-8031-cce8710c9070.jpg)

**Comment by flibbertigibbet** [comment]
I think overridding the layout XML to set the following on  `form_elements_container` should do it:
```
android:layout_gravity="start"
android:textDirection="locale"
```

**Comment by ghazalarabi** [comment]
thank you but it doesn't work. 
![22](https://cloud.githubusercontent.com/assets/8850937/21099787/7a446206-c085-11e6-995e-bb0a0fdd9029.jpg)

**Comment by ghazalarabi** [comment]
somehow i solved my problem.but there is another problem with SelectionController. i couldn't change the string prompt.it is always "select".
![1](https://cloud.githubusercontent.com/assets/8850937/21293935/fbe13b84-c546-11e6-8703-1fa4fc05f0c9.png)

**Comment by dkharrat** [comment]
@ghazalarabi For the benefit of others who run into a similar situation, can you share what you did to solve the issue?

**Comment by ghazalarabi** [comment]
I've just empty the label text and set the text of placeholder RTL.
But i couldn't find any way to solve prompt problem.is it possible to change the "select" word?

**Comment by dkharrat** [comment]
Regarding the "Select" placeholder, this is actually a bug. It's come from this file: [nothing_selected.xml](https://github.com/dkharrat/NexusDialog/blob/master/nexusdialog/src/main/res/layout/nothing_selected.xml). The `SelectionController` should be setting the text properly in the `nothing_selected.xml` layout.

**Comment by ghazalarabi** [comment]
thank you so much.
