### ISSUE TITLE
Failed to implement formFragment in Tablayout and Tabs, Please help

### ISSUE THREAD

**Issue by blackbirdsr71br** [dkharrat/NexusDialog#48]
Good afternoon.

This library is great.

But when implementing the new formFragment feature in a Tablayout, viewpargeradapter and tabs, I get an error when I try to capture in the form's controls, a null error, either in the text or in the select.

There is some special way for this feature to work correctly in the viewpageradapter and tablayout tab.

Thank you.

**Comment by dkharrat** [comment]
Can you provide a sample app that shows the problem?

**Comment by blackbirdsr71br** [comment]
Thank you very much for answering.

**# Attach the code that I use that gives me the problem.**

**# My Activity**

package com.github.dkharrat.nexusdialog.sample;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.design.widget.TabLayout;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.github.dkharrat.nexusdialog.FormController;
import com.github.dkharrat.nexusdialog.FormFragment;
import com.github.dkharrat.nexusdialog.FormInitializer;
import com.github.dkharrat.nexusdialog.FormManager;
import com.github.dkharrat.nexusdialog.FormModel;
import com.github.dkharrat.nexusdialog.controllers.CheckBoxController;
import com.github.dkharrat.nexusdialog.controllers.EditTextController;
import com.github.dkharrat.nexusdialog.controllers.FormSectionController;
import com.github.dkharrat.nexusdialog.controllers.SelectionController;
import com.github.dkharrat.nexusdialog.utils.MessageUtil;

import java.util.Arrays;
import java.util.HashSet;


public class FragActivity extends AppCompatActivity {
    ViewPager pager;
    TabLayout tabLayout;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.frag_main);

        pager= (ViewPager) findViewById(R.id.view_pager);
        tabLayout= (TabLayout) findViewById(R.id.tab_layout);
        //Adding the tabs using addTab() method
        tabLayout.addTab(tabLayout.newTab().setText("Tab1"));
        tabLayout.addTab(tabLayout.newTab().setText("Tab2"));
        tabLayout.addTab(tabLayout.newTab().setText("Tab3"));
        tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);

        FragmentManager manager=getSupportFragmentManager();


        Pager adapter=new Pager(manager,3);
        pager.setAdapter(adapter);

        tabLayout.setupWithViewPager(pager);

        pager.addOnPageChangeListener(new TabLayout.TabLayoutOnPageChangeListener(tabLayout));

        tabLayout.setupWithViewPager(pager);

    }


}


**# My pager**

package com.github.dkharrat.nexusdialog.sample;

import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.app.FragmentStatePagerAdapter;

/**
 * Created by Belal on 2/3/2016.
 */
//Extending FragmentStatePagerAdapter
public class Pager extends FragmentPagerAdapter {

    //integer to count number of tabs
    int tabCount;

    //Constructor to the class
    public Pager(FragmentManager fm, int tabCount) {
        super(fm);
        //Initializing tab count
        this.tabCount= tabCount;
    }

    //Overriding method getItem
    @Override
    public Fragment getItem(int position) {
        //Returning the current tabs
        switch (position) {
            case 0:
                AlumFragment tab1 = new AlumFragment();
                return tab1;
            case 1:
                AlumgFragment tab2 = new AlumgFragment();
                return tab2;
            case 2:
                AlumtFragment tab3 = new AlumtFragment();
                return tab3;
            default:
                return null;
        }
    }

    //Overriden method getCount to get the number of tabs
    @Override
    public int getCount() {
        return tabCount;
    }

    @Override
    public CharSequence getPageTitle(int position) {
        String title=" ";
        switch (position){
            case 0:
                title="Generales";
                break;
            case 1:
                title="Adicionales";
                break;
            case 2:
                title="Balastro";
                break;
        }

        return title;
    }

}

**# And my Fragments**

package com.github.dkharrat.nexusdialog.sample;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.github.dkharrat.nexusdialog.FormController;
import com.github.dkharrat.nexusdialog.FormFragment;
import com.github.dkharrat.nexusdialog.FormInitializer;
import com.github.dkharrat.nexusdialog.FormManager;
import com.github.dkharrat.nexusdialog.FormModel;
import com.github.dkharrat.nexusdialog.controllers.CheckBoxController;
import com.github.dkharrat.nexusdialog.controllers.EditTextController;
import com.github.dkharrat.nexusdialog.controllers.FormSectionController;
import com.github.dkharrat.nexusdialog.controllers.SelectionController;
import com.github.dkharrat.nexusdialog.utils.MessageUtil;

import java.util.Arrays;
import java.util.HashSet;

/**
 * <code>FormFragment</code> provides a default Fragment implementation for using NexusDialog.
 */
public class AlumFragment extends FormFragment {

    private FormManager formManager;
    public static final String FIRST_NAME = "nombre";
    public static final String LAST_NAME = "apellido";
    public static final String GENDER = "gender";
    public static final String HOBBIES = "hobbies";

    @Override
    public void initForm(FormController controller) {
        Context ctxt = getContext();
        FormSectionController section = new FormSectionController(ctxt, "Personal Info");
        section.addElement(new EditTextController(ctxt, FIRST_NAME, "First name"));
        section.addElement(new EditTextController(ctxt, LAST_NAME, "Last name"));
        section.addElement(new SelectionController(ctxt, GENDER, "Gender", true, "Select", Arrays.asList("Male", "Female"), true));
        section.addElement(new CheckBoxController(ctxt, HOBBIES, "You like", true, Arrays.asList("sport", "gaming", "relaxation", "development"), true));

        HashSet<String> checkedBoxes = new HashSet<String>();
        checkedBoxes.add("gaming");
        controller.getModel().setValue("hobbies", checkedBoxes);

        controller.addSection(section);


    }

    public static final AlumFragment newInstance()
    {
        AlumFragment f = new AlumFragment();

        return f;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.alum_activity, null);

    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        formManager = new FormManager(this, this, R.id.form_elements_container);
        recreateViews();
    }

    public FormController getFormController() {
        return formManager.getFormController();
    }

    public FormModel getModel() {
        return getFormController().getModel();
    }

    protected void recreateViews() {
        formManager.recreateViews();
    }

    public boolean validate() {

        getFormController().resetValidationErrors();
        if (getFormController().isValidInput()) {
            Object firstName = getModel().getValue(FIRST_NAME);
            Object lastName = getModel().getValue(LAST_NAME);
            Object gender = getModel().getValue(GENDER);
            Object favColor = getModel().getValue(HOBBIES);

            String msg = "First name: " + firstName + "\n"
                    + "Last name: " + lastName + "\n"
                    + "Gender: " + gender + "\n"
                    + "Hobbies: " + favColor + "\n";
            MessageUtil.showAlertMessage("Field Values", msg, getActivity());
        } else {
            getFormController().showValidationErrors();
        }
        return true;
    }


}



**# Fragment 2**

package com.github.dkharrat.nexusdialog.sample;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.github.dkharrat.nexusdialog.FormController;
import com.github.dkharrat.nexusdialog.FormFragment;
import com.github.dkharrat.nexusdialog.FormInitializer;
import com.github.dkharrat.nexusdialog.FormManager;
import com.github.dkharrat.nexusdialog.FormModel;
import com.github.dkharrat.nexusdialog.controllers.CheckBoxController;
import com.github.dkharrat.nexusdialog.controllers.EditTextController;
import com.github.dkharrat.nexusdialog.controllers.FormSectionController;
import com.github.dkharrat.nexusdialog.controllers.SelectionController;
import com.github.dkharrat.nexusdialog.utils.MessageUtil;

import java.util.Arrays;
import java.util.HashSet;

/**
 * <code>FormFragment</code> provides a default Fragment implementation for using NexusDialog.
 */
public class AlumtFragment extends FormFragment {

    private FormManager formManager1;
    public static final String FIRST_NAME = "nombre";
    public static final String LAST_NAME = "apellido";
    public static final String GENDER = "gender";
    public static final String HOBBIES = "hobbies";

    @Override
    public void initForm(FormController controller) {
        Context ctxt = getContext();
        FormSectionController section = new FormSectionController(ctxt, "Personal Info");
        section.addElement(new EditTextController(ctxt, FIRST_NAME, "First name"));
        section.addElement(new EditTextController(ctxt, LAST_NAME, "Last name"));
        section.addElement(new SelectionController(ctxt, GENDER, "Gender", true, "Select", Arrays.asList("Male", "Female"), true));
        section.addElement(new CheckBoxController(ctxt, HOBBIES, "You like", true, Arrays.asList("sport", "gaming", "relaxation", "development"), true));

        HashSet<String> checkedBoxes = new HashSet<String>();
        checkedBoxes.add("gaming");
        controller.getModel().setValue("hobbies", checkedBoxes);

        controller.addSection(section);


    }

    public static final AlumtFragment newInstance()
    {
        AlumtFragment f = new AlumtFragment();

        return f;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.alumt_activity, null);

    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        formManager1 = new FormManager(this, this, R.id.form_elements_container2);
        recreateViews();
    }

    public FormController getFormController() {
        return formManager1.getFormController();
    }

    public FormModel getModel() {
        return getFormController().getModel();
    }

    protected void recreateViews() {
        formManager1.recreateViews();
    }

    public boolean validate() {

        getFormController().resetValidationErrors();
        if (getFormController().isValidInput()) {
            Object firstName = getModel().getValue(FIRST_NAME);
            Object lastName = getModel().getValue(LAST_NAME);
            Object gender = getModel().getValue(GENDER);
            Object favColor = getModel().getValue(HOBBIES);

            String msg = "First name: " + firstName + "\n"
                    + "Last name: " + lastName + "\n"
                    + "Gender: " + gender + "\n"
                    + "Hobbies: " + favColor + "\n";
            MessageUtil.showAlertMessage("Field Values", msg, getActivity());
        } else {
            getFormController().showValidationErrors();
        }
        return true;
    }


}

**Comment by ShaznaM** [comment]
this issue is there !
