### ISSUE TITLE
Initialize fields to certain values not work with FormWithAppCompatActivity

### ISSUE THREAD

**Issue by khaaaniii** [dkharrat/NexusDialog#49]
the getmodel() method return null as model in initForm and so we cannot initialize fields !!!!!

**Comment by manurana** [comment]
use it in this way
if you don't use the reference to the controller, you will get a crash
```java
controller.getModel().setValue("first_name", "John");
```

**Comment by dkharrat** [comment]
This is fixed in the latest release.
