### ISSUE TITLE
How to dynamically add new elements?

### ISSUE THREAD

**Issue by hasanmumin** [dkharrat/NexusDialog#5]
How to dynamically add new elements? for example on PropertyChangeListener. 
PropertyChangeListener type = new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent event) {

                Object type = getModel().getValue("type");

                if (type.equals("new")) {
                    section.addElement(new EditTextController(context, "test", "First name", "Change me"));
                    getFormController().refreshElements();
                }
            }
        };
 getModel().addPropertyChangeListener("type", type);

i am getting null pointer exception Can you help me ?

**Comment by dkharrat** [comment]
Thanks for reporting this issue. It is now fixed in version 0.3.0. Take a look at the sample project for an example, but essentially you need to call `recreateViews()` after adding/removing an element dynamically.

**Comment by hasanmumin** [comment]
Thank you for your speedy return. May be you can adding show/hide configuration for element or when adding element to FormSectionController congigurable (elementName,hidden for example **section.addElement(new EditTextController(this, "firstName", "First name"),*false*);**). It would be easier for some users. Thanks again for fixed my issue.
