### ISSUE TITLE
Library maintenance

### ISSUE THREAD

**Issue by dneykov** [dkharrat/NexusDialog#58]
I'm planning to use this library but I saw that there are no commits recently. Is it still maintained?
Thanks

**Comment by dkharrat** [comment]
I'm still maintaining it, but I haven't found a need to implement new functionality recently. I do review and merge any PRs that are submitted.

**Comment by dneykov** [comment]
I tried your library and I'm going to use it. I need one functionality that I'm not sure how can I achive it. I have a form where I need to add up to 4 images. Can you give me suggestion for custom row which support taking pictures with camera or selecting existing ones. 
Thanks.

**Comment by flibbertigibbet** [comment]
Here's [an example](https://github.com/azavea/AndroidValidatedForms/blob/develop/androidvalidatedforms/src/main/java/com/azavea/androidvalidatedforms/controllers/ImageController.java) of an image controller on a fork of this library.

**Comment by dneykov** [comment]
@flibbertigibbet Thank you so much. This is exactly what I need.

**Comment by dkharrat** [comment]
@dneykov the library is designed to be extensible, so you should be able to implement custom rows by inheriting the `FormElementController` class. Take a look at implementation for the provided rows for examples.

@flibbertigibbet thanks for providing an example! It would be great if you could submit pull requests for any generic functionality that you've implemented.
