### ISSUE TITLE
How to Enable and disable the controls

### ISSUE THREAD

**Issue by powellbird** [dkharrat/NexusDialog#62]
## Como abilitar y desabilitar los controles.

Buenos dias, la libreria es genial y aun mas con las modificaciones que se han hecho ultimamente, quisiera saber como puedo abilitar y desabilitarlos controles y si tienen algun ejemplo, gracias y saludos.

**Comment by dkharrat** [comment]
I don't read spanish, but from the title it looks like you're asking how to enable/disable controls. The library doesn't provide a direct way to do it, but you can do it from the associated `View. See [this comment](https://github.com/dkharrat/NexusDialog/pull/4#issuecomment-314048555) for an example. A pull request is welcome.
