### ISSUE TITLE
Using Edittext inside of TextInputLayout

### ISSUE THREAD

**Issue by catkbm** [dkharrat/NexusDialog#64]

**Comment by catkbm** [comment]
How can i use the Edittext inside of TextInputLayout, please let me know as soon as possible

**Comment by dkharrat** [comment]
TextInputLayout is a new feature in recent Android versions, so it's not currently supported in NexusDialog. You would need to implement a custom control for for it.

A PR to support it in `EditTextController` is welcome.

**Comment by catkbm** [comment]
Okay thanks for your kind response
