### ISSUE TITLE
Changing selection options after Async task?

### ISSUE THREAD

**Issue by elprl** [dkharrat/NexusDialog#7]
I'm loading a SelectionController with an empty array:
`section2.addElement(new SelectionController(this, "pet", "pet", true, "Loading...", new ArrayList<String>(), true));`
Then I perform a background operation to grab a list from the internet. How do I then update that element dynamically with the new options to choose?

**Comment by dkharrat** [comment]
Unfortunately, this is not currently supported, but I do agree it's an important use-case. I'll leave this issue  open to track it. A pull request is also welcome :)

**Comment by elprl** [comment]
I actually got around this by adding a label element that says "Loading..." then after the task is completed, I removed that element and added a new SelectionController to that section.
