### ISSUE TITLE
removeElement no effect

### ISSUE THREAD

**Issue by muziling** [dkharrat/NexusDialog#8]
https://github.com/dkharrat/NexusDialog/blob/88978bdb58f81230d2c3778509b09fcce2bfce69/nexusdialog/src/main/java/com/github/dkharrat/nexusdialog/controllers/FormSectionController.java

public FormElementController removeElement(FormElementController element) {
        return elements.remove(element.getName());
    }

maybe need to add orderedElements.remove(element);

or just change to 
public FormElementController removeElement(FormElementController element) {
        return removeElement(element.getName());
    }

**Comment by dkharrat** [comment]
Good catch! You're right, this is a bug. Should be:

    public FormElementController removeElement(FormElementController element) {
        return removeElement(element.getName());
    }

I'll fix this in the next release.
